### AUTH

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "mikel",
  "email": "mikel1@fwseries.com",
  "password": "1234"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mikel1@fwseries.com",
  "password": "1234"
}

###

GET http://localhost:3000/api/characters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNmExMDM4MzJkODRkOTgxOWExYzI0YzA4IiwiaWF0IjoxNzc5NDQ3OTM3LCJleHAiOjE3ODAwNTI3Mzd9.EHiMnlJiOTAg7k1VU63Rj0PAzIKsZ7-0RimEywA5Pn0

###
